### ISSUE TITLE
docs: add a readme

### ISSUE THREAD

**Issue by gitcpy** [PlayerMiller109/obsidian-markmap-fileviews#1]
I like your plugin. But I don't know how to start. Could you kindly make a readme, please？

**Comment by PlayerMiller109** [comment]
Oh I wrote them in the forum [Exportable Markdown Mindmap](https://forum.obsidian.md/t/exportable-markdown-mindmap/86106). Did you find my repo directly in GitHub?

**Comment by gitcpy** [comment]
明白了，那我们可以用中文交流了，是这样的，我用brat安装了你这个插件，右上角有冒泡提示已经安装，但是我在设置里搜不到，然后阅读了你的文档
https://forum-zh.obsidian.md/t/topic/37790，
看不明白 ”通过命令创建当前活动文档的 Markmap 视图，默认快捷键 Ctrl + M。”，这里的命令是什么命令，快捷ctrl+m，也没起作用，请问这个插件是需要什么依赖才能运行吗？

**Comment by gitcpy** [comment]
看到了，可能是我这边的原因，现在看到这个插件了，我继续看看怎么使用，谢谢回复
